name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: create and push an image
        run: |
          chmod +x ./build.sh
          if [ "${GITHUB_REF##*/}" == "master" ]; then
            VERSION="3.1.${GITHUB_RUN_NUMBER}"
          else
            BRANCH_TO_DOCKER=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]//g')
            VERSION="$BRANCH_TO_DOCKER-${GITHUB_RUN_NUMBER}"
          fi
          sudo ./build.sh "quay.io" "sdase" "defectdojo-client" "${VERSION}" "${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}" "${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}" true