name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: create and push an image upload-client
        run: |
          cd upload-client
          chmod +x ./gradlew

          if [ "${GITHUB_REF##*/}" == "master" ]; then
            VERSION="3.1.${GITHUB_RUN_NUMBER}"
          else
            BRANCH_TO_DOCKER=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]//g')
            VERSION="$BRANCH_TO_DOCKER-${GITHUB_RUN_NUMBER}"
          fi
          MAJOR=$(echo "${VERSION}" | tr  '.' "\n" | sed -n 1p)
          MINOR=$(echo "${VERSION}" | tr  '.' "\n" | sed -n 2p)

          ./gradlew jib \
            -Djib.to.image=quay.io/sdase/defectdojo-client:${MAJOR}.${MINOR} \
            -Djib.to.auth.username="${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}" \
            -Djib.to.auth.password="${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}"
          ./gradlew jib \
            -Djib.to.image=quay.io/sdase/defectdojo-client:${MAJOR} \
            -Djib.to.auth.username="${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}" \
            -Djib.to.auth.password="${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}"
          ./gradlew jib \
            -Djib.to.image=quay.io/sdase/defectdojo-client:${VERSION} \
            -Djib.to.auth.username="${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}" \
            -Djib.to.auth.password="${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}"
      - name: create and push an image statistic-client
        run: |
          cd statistic-client
          chmod +x ./gradlew

          if [ "${GITHUB_REF##*/}" == "master" ]; then
            VERSION="3.1.${GITHUB_RUN_NUMBER}"
          else
            BRANCH_TO_DOCKER=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]//g')
            VERSION="$BRANCH_TO_DOCKER-${GITHUB_RUN_NUMBER}"
          fi
          MAJOR=$(echo "${VERSION}" | tr  '.' "\n" | sed -n 1p)
          MINOR=$(echo "${VERSION}" | tr  '.' "\n" | sed -n 2p)          

          ./gradlew jib \
            -Djib.to.image=quay.io/sdase/defectdojo-statistic-client:${MAJOR}.${MINOR} \
            -Djib.to.auth.username="${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}" \
            -Djib.to.auth.password="${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}"
          ./gradlew jib \
            -Djib.to.image=quay.io/sdase/defectdojo-statistic-client:${MAJOR} \
            -Djib.to.auth.username="${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}" \
            -Djib.to.auth.password="${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}"          
          ./gradlew jib \
            -Djib.to.image=quay.io/sdase/defectdojo-statistic-client:${VERSION} \
            -Djib.to.auth.username="${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}" \
            -Djib.to.auth.password="${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}"          
